# Generated by Django 4.0.5 on 2022-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_comments_options_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватар пользователя'),
        ),
    ]
